# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    mkdir ~/.ssh
    touch ~/.ssh/known_hosts
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    cd ~
    git clone --recurse-submodules https://github.com/zvory/dotfiles.git .dotfiles
    cd .dotfiles
    ./install
  displayName: 'Install'
