#!/usr/bin/env bash

set -e


CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo '#######################################'
echo '# Manual installation required for:'
echo '# add source ~/.aliases to ~/.zshrc'
echo '# fzf'
echo '# add source plugins=(git colored-man-pages z zsh-interactive-cd) to ~/.zshrc'
echo '#######################################'